# Generated by Django 6.0.6 on 2026-06-06 05:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('renta', 'Renta'), ('sueldos', 'Sueldos'), ('mercadotecnia', 'Mercadotecnia'), ('servicios', 'Servicios (luz, agua, internet)'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('monto_mensual', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monto mensual ($)')),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Costo fijo',
                'verbose_name_plural': 'Costos fijos (mensuales)',
                'ordering': ['categoria', 'concepto'],
            },
        ),
        migrations.CreateModel(
            name='InversionInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('equipo', 'Equipo (licuadora, congelador...)'), ('mobiliario', 'Mobiliario'), ('deposito', 'Depósito / Garantía renta'), ('permisos', 'Permisos y licencias'), ('inventario', 'Inventario inicial'), ('adecuacion', 'Adecuación del local'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monto ($)')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('notas', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Inversión inicial',
                'verbose_name_plural': 'Inversión inicial',
                'ordering': ['categoria', 'concepto'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoEfectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (+)'), ('salida', 'Salida (−)')], max_length=10)),
                ('concepto', models.CharField(max_length=120)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monto ($)')),
            ],
            options={
                'verbose_name': 'Movimiento de efectivo',
                'verbose_name_plural': 'Movimientos de efectivo (extra)',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
