# Generated by Django 6.0.6 on 2026-07-02 05:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_movimiento'),
        ('finanzas', '0002_pronosticoflujo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PronosticoFlujoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)], verbose_name='Año')),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monto pronosticado ($)')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronosticos_flujo', to='contabilidad.cuenta')),
            ],
            options={
                'verbose_name': 'Pronóstico de flujo por cuenta',
                'verbose_name_plural': 'Pronóstico de flujo (por cuenta y mes)',
                'ordering': ['-anio', '-mes', 'cuenta'],
                'unique_together': {('anio', 'mes', 'cuenta')},
            },
        ),
        migrations.DeleteModel(
            name='PronosticoFlujo',
        ),
    ]
