# Generated by Django 6.0.6 on 2026-06-06 04:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Ingrediente')),
                ('categoria', models.CharField(choices=[('liquido', 'Base líquida'), ('proteina', 'Proteína Habits'), ('fruta', 'Fruta'), ('spread', 'Spread / Crema'), ('superfood', 'Superfood / Especia'), ('otro', 'Otro'), ('empaque', 'Empaque')], default='otro', max_length=20)),
                ('unidad_compra', models.CharField(help_text='Ej. kg, litro, paquete, rollo', max_length=30, verbose_name='Unidad de compra')),
                ('cantidad_por_unidad', models.DecimalField(decimal_places=2, help_text='Cuántas unidades de receta trae una unidad de compra. Ej. 1 kg = 1000 g; 1 paquete = 50 piezas.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Cantidad por unidad de compra')),
                ('unidad_receta', models.CharField(help_text='Ej. g, ml, pieza', max_length=20, verbose_name='Unidad de receta')),
                ('costo_unidad_compra', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo por unidad de compra ($)')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Shake')),
                ('emoji', models.CharField(blank=True, max_length=8)),
                ('perfil', models.CharField(blank=True, max_length=200, verbose_name='Perfil / descripción')),
                ('tamano', models.CharField(default='16 oz / 473 ml', max_length=40, verbose_name='Tamaño')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio de venta ($)')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cantidad comprada (en unidad de compra)')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo unitario ($)')),
                ('proveedor', models.CharField(blank=True, max_length=120)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='inventario.ingrediente')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Si lo dejas vacío se usa el precio de la receta.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio unitario ($)')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='inventario.receta')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RecetaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cantidad (en unidad de receta)')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='inventario.ingrediente')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='inventario.receta')),
            ],
            options={
                'verbose_name': 'Ingrediente de receta',
                'verbose_name_plural': 'Ingredientes de la receta',
                'unique_together': {('receta', 'ingrediente')},
            },
        ),
    ]
