# Generated by Django 6.0.6 on 2026-06-07 02:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cuánto se usa de ese ingrediente por cada extra agregado.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cantidad por porción (en unidad de receta)')),
                ('cargo', models.DecimalField(decimal_places=2, help_text='Cuánto se suma al precio de venta por este extra.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cargo extra al precio ($)')),
                ('activo', models.BooleanField(default=True)),
                ('ingrediente', models.ForeignKey(help_text='Ingrediente que consume del inventario.', on_delete=django.db.models.deletion.PROTECT, related_name='extras', to='inventario.ingrediente')),
            ],
            options={
                'verbose_name': 'Extra',
                'verbose_name_plural': 'Extras (catálogo)',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='VentaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cuántas porciones de este extra.')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.extra')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='inventario.venta')),
            ],
            options={
                'verbose_name': 'Extra de venta',
                'verbose_name_plural': 'Extras de la venta',
            },
        ),
        migrations.CreateModel(
            name='VentaSustitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente_nuevo', models.ForeignKey(help_text='Ingrediente que entra en su lugar.', on_delete=django.db.models.deletion.PROTECT, related_name='sustituto_en', to='inventario.ingrediente')),
                ('ingrediente_original', models.ForeignKey(help_text='Ingrediente de la receta que se quita.', on_delete=django.db.models.deletion.PROTECT, related_name='sustituido_en', to='inventario.ingrediente')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sustituciones', to='inventario.venta')),
            ],
            options={
                'verbose_name': 'Sustitución',
                'verbose_name_plural': 'Sustituciones',
            },
        ),
    ]
