# Generated by Django 6.0.6 on 2026-08-01 02:39

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_venta_metodo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateField()),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=10, verbose_name='Método de pago')),
                ('pago_con', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Paga con ($)')),
                ('cambio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cambio ($)')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Total ($)')),
            ],
            options={
                'verbose_name': 'Nota / comprobante',
                'verbose_name_plural': 'Notas / comprobantes',
                'ordering': ['-creada'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='nota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas', to='inventario.nota'),
        ),
    ]
