# Generated by Django 6.0.6 on 2026-08-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_nota_venta_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='es_cortesia',
            field=models.BooleanField(default=False, verbose_name='Cortesía'),
        ),
        migrations.AddField(
            model_name='nota',
            name='motivo_cortesia',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo de la cortesía'),
        ),
        migrations.AddField(
            model_name='venta',
            name='es_cortesia',
            field=models.BooleanField(default=False, help_text='Producto regalado (activación): sin ingreso, pero consume inventario.', verbose_name='Cortesía'),
        ),
    ]
