# Generated by Django 6.0.6 on 2026-08-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_nota_es_cortesia_nota_motivo_cortesia_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['fecha'], name='inventario__fecha_ecf680_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha'], name='inventario__fecha_2f5250_idx'),
        ),
    ]
