# Generated by Django 6.1 on 2026-08-13 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_capas_y_costo_fifo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAlarmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_caida_margen', models.PositiveSmallIntegerField(default=10, help_text='Caída respecto al mes anterior a partir de la cual se enciende la alarma. 10 = de 60% a 54% ya avisa.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Avisar si el margen baja (%)')),
            ],
            options={
                'verbose_name': 'Configuración de alarmas',
                'verbose_name_plural': 'Configuración de alarmas',
            },
        ),
    ]
