# Generated by Django 6.1 on 2026-08-17 00:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_pedidos_con_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento_pct',
            field=models.DecimalField(db_default=Decimal('0'), decimal_places=2, default=Decimal('0'), help_text='Rebaja sobre el precio de lista. No cambia el costo: solo baja lo que se cobró.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Descuento (%)'),
        ),
    ]
