# Generated by Django 6.1 on 2026-08-17 00:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_descuento_en_la_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumocapa',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='inventario.venta'),
        ),
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('cantidad_calculada', models.DecimalField(decimal_places=4, editable=False, help_text='Congelado al momento del conteo: el stock de mañana ya no explica la merma de hoy.', max_digits=14, verbose_name='Lo que el sistema calculaba')),
                ('cantidad_real', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Lo que hay de verdad')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Lo que valía lo que se perdió, según las capas que lo surtieron. Vacío mientras no se ha costeado.', max_digits=12, null=True, verbose_name='Costo de la merma ($)')),
                ('costo_incompleto', models.BooleanField(default=False, editable=False, help_text='Faltaban capas para respaldar parte de lo perdido.')),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='inventario.ingrediente')),
            ],
            options={
                'verbose_name': 'Ajuste de inventario (merma)',
                'verbose_name_plural': 'Ajustes de inventario (mermas)',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='consumocapa',
            name='ajuste',
            field=models.ForeignKey(blank=True, help_text='La merma que se llevó estas unidades, si no fue una venta.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='inventario.ajusteinventario'),
        ),
        migrations.AddIndex(
            model_name='consumocapa',
            index=models.Index(fields=['ajuste'], name='inventario__ajuste__0c6e74_idx'),
        ),
        migrations.AddConstraint(
            model_name='consumocapa',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ajuste__isnull', True), ('venta__isnull', False)), models.Q(('ajuste__isnull', False), ('venta__isnull', True)), _connector='OR'), name='consumo_de_una_venta_o_de_un_ajuste'),
        ),
        migrations.AddIndex(
            model_name='ajusteinventario',
            index=models.Index(fields=['fecha'], name='inventario__fecha_100ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='ajusteinventario',
            index=models.Index(fields=['ingrediente', 'fecha'], name='inventario__ingredi_170022_idx'),
        ),
    ]
