# Generated by Django 6.0.6 on 2026-06-06 05:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)], verbose_name='Año')),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes')),
                ('categoria', models.CharField(choices=[('insumos', 'Insumos / Mercancía'), ('renta', 'Renta'), ('servicios', 'Servicios'), ('mercadotecnia', 'Mercadotecnia'), ('sueldos', 'Sueldos'), ('otro', 'Otro gasto')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Meta de gasto ($)')),
                ('notas', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Presupuesto de gasto',
                'verbose_name_plural': 'Presupuesto de gastos (por categoría y mes)',
                'ordering': ['-anio', '-mes', 'categoria'],
                'unique_together': {('anio', 'mes', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='PresupuestoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)], verbose_name='Año')),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Meta de ventas ($)')),
                ('notas', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Presupuesto de ventas',
                'verbose_name_plural': 'Presupuesto de ventas (por mes)',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('anio', 'mes')},
            },
        ),
    ]
