# Generated by Django 6.0.6 on 2026-08-03 00:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0007_compra_inventario__fecha_ecf680_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(default='Habits Shakes', max_length=80)),
                ('activo', models.BooleanField(default=True, help_text='Si lo apagas, las ventas dejan de acumular puntos.', verbose_name='Programa activo')),
                ('pesos_por_punto', models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='$10 = 1 punto. Una compra de $130 otorga 13 puntos.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Pesos por punto')),
                ('vigencia_puntos_meses', models.PositiveSmallIntegerField(default=12, help_text='0 = los puntos nunca caducan.', verbose_name='Vigencia de los puntos (meses)')),
                ('aviso_expiracion_dias', models.PositiveSmallIntegerField(default=15, verbose_name='Avisar antes de que caduquen (días)')),
                ('dias_inactividad', models.PositiveSmallIntegerField(default=30, verbose_name='Días sin comprar para considerar inactivo')),
                ('ventana_atribucion_dias', models.PositiveSmallIntegerField(default=7, help_text='Compras dentro de este plazo tras un mensaje cuentan como venta atribuida a ese mensaje.', verbose_name='Ventana de atribución (días)')),
                ('site_url', models.URLField(blank=True, help_text='Ej. https://lealtad.tunegocio.mx — se usa en los enlaces que se le mandan al cliente. Vacío = se deduce del request.', verbose_name='Dirección pública del sitio')),
                ('proveedor_mensajes', models.CharField(choices=[('simulado', 'Simulado (no envía, solo registra)'), ('whatsapp', 'WhatsApp Business API (Meta)'), ('twilio', 'Twilio (SMS)')], default='simulado', max_length=20, verbose_name='Enviar mensajes por')),
                ('envio_hora_inicio', models.PositiveSmallIntegerField(default=9, validators=[django.core.validators.MaxValueValidator(23)], verbose_name='No enviar antes de (hora)')),
                ('envio_hora_fin', models.PositiveSmallIntegerField(default=21, validators=[django.core.validators.MaxValueValidator(23)], verbose_name='No enviar después de (hora)')),
                ('api_token', models.CharField(blank=True, help_text='Requerido en el encabezado Authorization: Bearer <token> para que un ERP externo registre compras.', max_length=64, verbose_name='Token de la API')),
            ],
            options={
                'verbose_name': 'Configuración del programa',
                'verbose_name_plural': 'Configuración del programa',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('emoji', models.CharField(blank=True, max_length=8)),
                ('puntos_requeridos', models.PositiveIntegerField(default=0, verbose_name='Puntos históricos requeridos')),
                ('beneficios', models.TextField(blank=True, help_text='Qué obtiene el cliente en este nivel.')),
                ('color', models.CharField(default='#fa5598', help_text='Color de la tarjeta digital en este nivel.', max_length=9)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
                'ordering': ['puntos_requeridos'],
            },
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(help_text="Identificador interno, ej. 'bienvenida'.", unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='whatsapp', max_length=10)),
                ('cuerpo', models.TextField(help_text='Ej. ¡Hola {nombre}! Tu saldo es de {saldo} puntos.')),
                ('plantilla_meta', models.CharField(blank=True, help_text='Solo para WhatsApp fuera de la ventana de 24 h. Debe existir aprobada en tu WhatsApp Business.', max_length=80, verbose_name='Nombre de la plantilla en Meta')),
                ('idioma_meta', models.CharField(default='es_MX', max_length=10)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plantilla de mensaje',
                'verbose_name_plural': 'Plantillas de mensaje',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PromocionPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('multiplicador', models.DecimalField(decimal_places=2, default=Decimal('2'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Promoción de puntos',
                'verbose_name_plural': 'Promociones de puntos',
                'ordering': ['-desde'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(help_text='Se guarda en formato internacional (+52...).', max_length=20, unique=True, verbose_name='Celular')),
                ('nombre', models.CharField(blank=True, max_length=80, verbose_name='Nombre')),
                ('cumpleanos', models.DateField(blank=True, null=True, verbose_name='Cumpleaños')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('puntos_saldo', models.IntegerField(default=0, verbose_name='Puntos disponibles')),
                ('puntos_historicos', models.PositiveIntegerField(default=0, verbose_name='Puntos acumulados de por vida')),
                ('gasto_historico', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Gasto acumulado ($)')),
                ('visitas', models.PositiveIntegerField(default=0)),
                ('alta', models.DateTimeField(auto_now_add=True)),
                ('ultima_compra', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('baja', 'Dado de baja')], default='activo', max_length=10)),
                ('acepta_mensajes', models.BooleanField(default=True, verbose_name='Acepta recibir mensajes')),
                ('origen', models.CharField(choices=[('caja', 'Registrado en caja'), ('autoservicio', 'Se registró él mismo (QR)'), ('api', 'Alta por API'), ('manual', 'Alta manual')], default='caja', max_length=15)),
                ('notas', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-alta'],
                'indexes': [models.Index(fields=['ultima_compra'], name='lealtad_cli_ultima__ed69ee_idx'), models.Index(fields=['puntos_historicos'], name='lealtad_cli_puntos__acde28_idx')],
            },
        ),
        migrations.CreateModel(
            name='Canje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_usados', models.PositiveIntegerField()),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de entregar'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado (puntos devueltos)'), ('expirado', 'Expirado')], default='pendiente', max_length=10)),
                ('vence_el', models.DateField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('entregado_en', models.DateTimeField(blank=True, null=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canjes_autorizados', to=settings.AUTH_USER_MODEL)),
                ('nota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canjes', to='inventario.nota')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes', to='lealtad.cliente')),
            ],
            options={
                'verbose_name': 'Canje de premio',
                'verbose_name_plural': 'Canjes de premios',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(blank=True, help_text='Folio del ERP externo. Evita registrar dos veces la misma venta.', max_length=40, verbose_name='Número de ticket')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('puntos_ganados', models.PositiveIntegerField(default=0)),
                ('multiplicador', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=4)),
                ('fecha', models.DateField()),
                ('origen', models.CharField(choices=[('caja', 'Caja'), ('api', 'API / ERP externo'), ('manual', 'Captura manual')], default='caja', max_length=10)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='lealtad.cliente')),
                ('nota', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compra_lealtad', to='inventario.nota')),
            ],
            options={
                'verbose_name': 'Compra del programa',
                'verbose_name_plural': 'Compras del programa',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('gana', 'Ganó puntos'), ('canje', 'Canjeó un premio'), ('ajuste', 'Ajuste manual'), ('expira', 'Puntos caducados')], max_length=10)),
                ('puntos', models.IntegerField(help_text='Positivo suma, negativo resta.')),
                ('saldo_lote', models.IntegerField(default=0, help_text="Puntos que quedan sin consumir en este lote (solo 'gana').")),
                ('expira_el', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=160)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('canje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='lealtad.canje')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='lealtad.cliente')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='lealtad.compra')),
            ],
            options={
                'verbose_name': 'Movimiento de puntos',
                'verbose_name_plural': 'Movimientos de puntos',
                'ordering': ['-creado', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('segmento', models.CharField(choices=[('todos', 'Todos los clientes'), ('activos', 'Clientes activos'), ('inactivos', 'Clientes inactivos'), ('nivel', 'De un nivel en específico'), ('cerca_premio', 'Cerca de un premio'), ('cumpleaneros', 'Cumpleañeros del mes'), ('nuevos', 'Nuevos (últimos 30 días)')], default='todos', max_length=15)),
                ('cuerpo', models.TextField(blank=True, help_text='Si lo llenas, se usa en vez de la plantilla.')),
                ('programada_para', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('programada', 'Programada'), ('enviada', 'Enviada'), ('cancelada', 'Cancelada')], default='borrador', max_length=12)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas', to='lealtad.nivel')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas', to='lealtad.plantilla')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='Automatizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('disparador', models.CharField(choices=[('bienvenida', 'Al registrarse'), ('primera_compra', 'Al hacer su primera compra'), ('compra', 'Cada vez que compra'), ('premio_disponible', 'Cuando ya puede canjear un premio'), ('nivel', 'Al alcanzar un nivel'), ('cerca_premio', 'Cuando está cerca de un premio'), ('inactividad', 'Cuando lleva días sin comprar'), ('cumpleanos', 'Antes de su cumpleaños'), ('por_expirar', 'Cuando sus puntos están por caducar')], max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('umbral_porcentaje', models.PositiveSmallIntegerField(default=80, help_text="Solo para 'está cerca de un premio'.", validators=[django.core.validators.MaxValueValidator(100)], verbose_name='% de avance al premio')),
                ('dias', models.PositiveSmallIntegerField(default=30, help_text='Días sin comprar, o días antes del cumpleaños, o días antes de que caduquen los puntos.', verbose_name='Días')),
                ('hora_envio', models.PositiveSmallIntegerField(default=11, help_text='Solo aplica a los disparadores programados.', validators=[django.core.validators.MaxValueValidator(23)], verbose_name='Hora de envío')),
                ('dias_semana', models.CharField(default='0123456', help_text='Días de la semana en los que se permite enviar.', max_length=7, verbose_name='Días permitidos')),
                ('no_repetir_dias', models.PositiveSmallIntegerField(default=30, help_text='0 = se puede repetir siempre.', verbose_name='No repetir al mismo cliente en (días)')),
                ('max_por_cliente', models.PositiveSmallIntegerField(default=0, help_text='0 = sin límite.', verbose_name='Máximo de veces por cliente')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('nivel_objetivo', models.ForeignKey(blank=True, help_text="Solo para 'al alcanzar un nivel'. Vacío = cualquier nivel.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automatizaciones', to='lealtad.nivel')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automatizaciones', to='lealtad.plantilla')),
            ],
            options={
                'verbose_name': 'Automatización',
                'verbose_name_plural': 'Automatizaciones',
                'ordering': ['disparador', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PaseWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(choices=[('google', 'Google Wallet'), ('apple', 'Apple Wallet')], max_length=10)),
                ('object_id', models.CharField(blank=True, max_length=120)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('sincronizado', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pases', to='lealtad.cliente')),
            ],
            options={
                'verbose_name': 'Pase de wallet',
                'verbose_name_plural': 'Pases de wallet',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='whatsapp', max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('cuerpo', models.TextField()),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('leido', 'Leído'), ('fallido', 'Falló'), ('cancelado', 'Cancelado')], default='programado', max_length=12)),
                ('programado_para', models.DateTimeField(default=django.utils.timezone.now)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('entregado_en', models.DateTimeField(blank=True, null=True)),
                ('leido_en', models.DateTimeField(blank=True, null=True)),
                ('proveedor_id', models.CharField(blank=True, max_length=80, verbose_name='ID del proveedor')),
                ('error', models.CharField(blank=True, max_length=200)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('automatizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='lealtad.automatizacion')),
                ('campana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='lealtad.campana')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='lealtad.cliente')),
                ('compra_atribuida', models.ForeignKey(blank=True, help_text='Primera compra del cliente dentro de la ventana tras recibir el mensaje.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_atribuidos', to='lealtad.compra')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='lealtad.plantilla')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Bandeja de mensajes',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('emoji', models.CharField(blank=True, max_length=8)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('puntos_requeridos', models.PositiveIntegerField(verbose_name='Cuesta (puntos)')),
                ('tipo', models.CharField(choices=[('producto', 'Producto gratis'), ('descuento_pct', 'Descuento en %'), ('descuento_monto', 'Descuento en $'), ('combo', 'Combo / varios productos'), ('libre', 'Otro (se describe en el texto)')], default='producto', max_length=20)),
                ('cantidad', models.PositiveSmallIntegerField(default=1, help_text='Cuántas unidades del producto incluye.')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Para descuento en %: 50 = mitad de precio. Para descuento en $: el monto. Para producto gratis: se ignora.', max_digits=10, verbose_name='Valor / porcentaje')),
                ('limite_por_cliente', models.PositiveSmallIntegerField(default=0, help_text='0 = sin límite.', verbose_name='Límite por cliente')),
                ('vigencia_dias', models.PositiveSmallIntegerField(default=30, help_text='Días que tiene el cliente para reclamarlo. 0 = sin límite.', verbose_name='Vigencia del canje (días)')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('nivel_minimo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premios', to='lealtad.nivel', verbose_name='Nivel mínimo')),
                ('receta', models.ForeignKey(blank=True, help_text='Producto que se regala o descuenta. Sirve para calcular solo el costo y el valor del premio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premios', to='inventario.receta')),
            ],
            options={
                'verbose_name': 'Premio',
                'verbose_name_plural': 'Premios',
                'ordering': ['orden', 'puntos_requeridos'],
            },
        ),
        migrations.AddField(
            model_name='canje',
            name='premio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canjes', to='lealtad.premio'),
        ),
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.UniqueConstraint(condition=models.Q(('ticket', ''), _negated=True), fields=('ticket',), name='lealtad_ticket_unico'),
        ),
        migrations.AddIndex(
            model_name='movimientopuntos',
            index=models.Index(fields=['cliente', 'tipo'], name='lealtad_mov_cliente_edf196_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientopuntos',
            index=models.Index(fields=['expira_el'], name='lealtad_mov_expira__2baeed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pasewallet',
            unique_together={('cliente', 'proveedor')},
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['estado', 'programado_para'], name='lealtad_men_estado_3c829e_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['cliente', 'automatizacion'], name='lealtad_men_cliente_645ff3_idx'),
        ),
    ]
