# Generated by Django 6.1 on 2026-08-13 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_configuracionalarmas'),
        ('lealtad', '0002_codigo_unico_y_devoluciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='canje',
            name='venta',
            field=models.OneToOneField(blank=True, help_text='La cortesía que sacó el premio del inventario. Solo para premios de producto o combo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canje', to='inventario.venta'),
        ),
        migrations.AddField(
            model_name='compra',
            name='nivel_alcanzado',
            field=models.ForeignKey(blank=True, help_text='El nivel que esta compra desbloqueó, si desbloqueó alguno. Se escribe al registrarla, cuando el dato se conoce.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_que_lo_desbloquearon', to='lealtad.nivel'),
        ),
    ]
