# Generated by Django 6.1 on 2026-08-13 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_configuracionalarmas'),
        ('lealtad', '0002_codigo_unico_y_devoluciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='canje',
            name='costo_real',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lo que costó entregarlo, por FIFO. Vacío = no se ha entregado, o el premio no consume inventario.', max_digits=12, null=True, verbose_name='Costo real ($)'),
        ),
        migrations.AddField(
            model_name='canje',
            name='venta',
            field=models.OneToOneField(blank=True, help_text='La cortesía que sacó el premio del inventario. Solo para premios de producto o combo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canje', to='inventario.venta'),
        ),
    ]
