# Generated by Django 6.1 on 2026-08-16 23:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lealtad', '0003_canje_venta_compra_nivel_alcanzado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescuentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='15 = 15% de descuento sobre el total.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Descuento (%)')),
                ('descripcion', models.CharField(blank=True, help_text='Convenio, empleado, cortesía de temporada…', max_length=200, verbose_name='Por qué')),
                ('desde', models.DateField(default=django.utils.timezone.localdate, verbose_name='Desde')),
                ('hasta', models.DateField(blank=True, help_text='Vacío = sin vencimiento.', null=True, verbose_name='Hasta')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='lealtad.cliente')),
            ],
            options={
                'verbose_name': 'Descuento de cliente',
                'verbose_name_plural': 'Descuentos de clientes',
                'ordering': ['-desde', '-id'],
                'indexes': [models.Index(fields=['activo', 'desde', 'hasta'], name='lealtad_des_activo_56e964_idx')],
            },
        ),
    ]
