# Generated by Django 6.0.6 on 2026-06-06 05:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=200)),
                ('referencia', models.CharField(blank=True, help_text='Origen del asiento (ej. Venta #12, Gasto #5).', max_length=80)),
                ('automatico', models.BooleanField(default=False, help_text='Generado automáticamente desde una venta o gasto.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asiento contable',
                'verbose_name_plural': 'Asientos contables (pólizas)',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('capital', 'Capital'), ('ingreso', 'Ingreso'), ('gasto', 'Gasto / Costo')], max_length=12)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Catálogo de cuentas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='FacturaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('folio', models.CharField(blank=True, max_length=40)),
                ('proveedor', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('insumos', 'Insumos / Mercancía'), ('renta', 'Renta'), ('servicios', 'Servicios'), ('mercadotecnia', 'Mercadotecnia'), ('sueldos', 'Sueldos'), ('otro', 'Otro gasto')], default='otro', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Monto antes de IVA.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Subtotal ($)')),
                ('aplica_iva', models.BooleanField(default=True, verbose_name='Aplica IVA 16%')),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('asiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura_gasto', to='contabilidad.asiento')),
            ],
            options={
                'verbose_name': 'Factura de gasto',
                'verbose_name_plural': 'Facturas de gasto',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FacturaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('folio', models.CharField(blank=True, max_length=40)),
                ('cliente', models.CharField(default='Público en general', max_length=120)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Monto antes de IVA.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Subtotal ($)')),
                ('aplica_iva', models.BooleanField(default=True, verbose_name='Aplica IVA 16%')),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('asiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura_venta', to='contabilidad.asiento')),
            ],
            options={
                'verbose_name': 'Factura de venta',
                'verbose_name_plural': 'Facturas de venta',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('haber', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='contabilidad.asiento')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='contabilidad.cuenta')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
    ]
