# Generated by Django 6.0.6 on 2026-06-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(help_text="Identificador corto (se genera del nombre), ej. 'logistica'.", max_length=30, unique=True, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('cuenta_codigo', models.CharField(blank=True, help_text="Cuenta del catálogo a la que se cargan estos gastos. Si se deja vacío se usa 'Otros gastos' (509).", max_length=20, verbose_name='Código de cuenta contable')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de gasto',
                'verbose_name_plural': 'Categorías de gasto',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='facturagasto',
            name='tipo',
            field=models.CharField(default='otro', max_length=30, verbose_name='Categoría'),
        ),
    ]
