# Generated by Django 6.0.6 on 2026-07-02 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_seed_categorias_gasto'),
        ('inventario', '0004_venta_metodo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra')], max_length=10)),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('facturado', models.BooleanField(default=False, verbose_name='Facturado')),
                ('fecha_factura', models.DateField(blank=True, null=True, verbose_name='Fecha de factura')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('asiento_flujo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.asiento')),
                ('asiento_reconocimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.asiento')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento', to='inventario.compra')),
                ('cuenta', models.ForeignKey(help_text='Cuenta de resultados afectada al facturar (ingreso o gasto).', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_libro', to='contabilidad.cuenta')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento', to='inventario.venta')),
            ],
            options={
                'verbose_name': 'Movimiento (libro)',
                'verbose_name_plural': 'Libro de movimientos',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
