# Generated by Django 6.0.6 on 2026-08-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_movimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaventa',
            name='asiento',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='categoria',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra'), ('gasto', 'Gasto operativo')], max_length=10),
        ),
        migrations.DeleteModel(
            name='FacturaGasto',
        ),
        migrations.DeleteModel(
            name='FacturaVenta',
        ),
    ]
