# Generated by Django 6.0.6 on 2026-08-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_remove_facturaventa_asiento_movimiento_categoria_and_more'),
        ('inventario', '0007_compra_inventario__fecha_ecf680_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asiento',
            index=models.Index(fields=['fecha'], name='contabilida_fecha_3506db_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['fecha'], name='contabilida_fecha_1f5075_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['tipo', 'facturado'], name='contabilida_tipo_205a47_idx'),
        ),
    ]
