"""
Django settings for habits_inventory project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(nombre, defecto):
    return os.environ.get(nombre, str(defecto)).lower() in ("1", "true", "yes", "on")


def _env_lista(nombre, defecto=""):
    """Lee una variable separada por comas. Los vacíos se descartan: sin ese
    filtro, una variable en blanco daría [""] en vez de []."""
    return [v.strip() for v in os.environ.get(nombre, defecto).split(",") if v.strip()]


# ── Configuración sensible (desde variables de entorno en producción) ─────────
# En desarrollo funciona sin configurar nada; en PRODUCCIÓN define:
#   DJANGO_DEBUG=0  DJANGO_SECRET_KEY=<clave>  DJANGO_ALLOWED_HOSTS=tu-dominio.com
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-!ilxestticw7ph83lpmhqbpke2ou5rgvp%w(9ohiudwq%stsv$",
)
# En Vercel siempre es producción, aunque falte la variable: si DEBUG quedara
# en True durante el build, collectstatic no generaría el manifiesto y en
# runtime TODAS las páginas darían 500 por "Missing staticfiles manifest entry".
DEBUG = os.environ.get("VERCEL") != "1" and _env_bool("DJANGO_DEBUG", True)
ALLOWED_HOSTS = _env_lista("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")
# Dominios desde los que se aceptan formularios (Vercel y/o dominio propio).
# Se listan explícitos a propósito: un comodín tipo https://*.vercel.app dejaría
# que cualquier proyecto de Vercel mandara peticiones a este sitio.
CSRF_TRUSTED_ORIGINS = _env_lista("DJANGO_CSRF_TRUSTED_ORIGINS")

# En producción no se permite arrancar con la clave insegura por defecto.
if not DEBUG and SECRET_KEY.startswith("django-insecure"):
    raise RuntimeError(
        "Configura DJANGO_SECRET_KEY (no uses la clave de desarrollo en producción).")

# Endurecimiento HTTPS/cookies solo cuando NO es modo desarrollo.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # Confía en el proxy inverso (Nginx) para el esquema HTTPS.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'reversion',
    'inventario',
    'finanzas',
    'contabilidad',
    'presupuesto',
    'lealtad',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',   # sirve estáticos en producción
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'reversion.middleware.RevisionMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'habits_inventory.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'habits_inventory.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Con DATABASE_URL definida se usa Postgres; sin ella, el SQLite de siempre.
# En producción NO hay respaldo a SQLite a propósito: el disco de Vercel es
# efímero, así que caer a SQLite significaría perder cada venta capturada.
DATABASE_URL = os.environ.get('DATABASE_URL', '')

if DATABASE_URL:
    import dj_database_url

    # El pooler de Supabase (puerto 6543, modo transaction) reparte cada
    # consulta entre backends distintos: no sobreviven ni los cursores de
    # servidor ni los prepared statements de psycopg3. Sin estos dos ajustes
    # el admin y los listados largos truenan de forma intermitente.
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL, conn_max_age=0, ssl_require=True,
            disable_server_side_cursors=True),
    }
    # prepare_threshold no es argumento de parse(): va en las OPTIONS que se
    # pasan tal cual a psycopg.connect().
    DATABASES['default'].setdefault('OPTIONS', {})['prepare_threshold'] = None
elif DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    raise RuntimeError(
        'Falta DATABASE_URL. En producción no se puede usar SQLite.')


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'   # destino de collectstatic (producción)
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        # En dev/tests: almacenamiento estándar (no requiere collectstatic).
        # En producción: WhiteNoise con manifiesto (cache-busting + compresión).
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage" if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

# Autenticación del sitio (paneles fuera del admin)
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'


# ── Programa de lealtad ──────────────────────────────────────────────────────
# Todo esto es opcional: sin nada configurado el programa funciona igual, con
# los mensajes en modo simulado y la tarjeta digital como página web.
#
# WhatsApp Business API (Meta Cloud API) — https://developers.facebook.com/apps
WHATSAPP_TOKEN = os.environ.get("WHATSAPP_TOKEN", "")
WHATSAPP_PHONE_NUMBER_ID = os.environ.get("WHATSAPP_PHONE_NUMBER_ID", "")
WHATSAPP_API_VERSION = os.environ.get("WHATSAPP_API_VERSION", "v21.0")
# El que tú inventas y capturas en Meta al dar de alta el webhook.
WHATSAPP_VERIFY_TOKEN = os.environ.get("WHATSAPP_VERIFY_TOKEN", "")

# Secreto del cron. Vercel lo manda en 'Authorization: Bearer <CRON_SECRET>'.
# Sin él, el endpoint del latido responde 503 en vez de correr.
CRON_SECRET = os.environ.get("CRON_SECRET", "")

# Twilio (SMS de respaldo)
TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN", "")
TWILIO_FROM = os.environ.get("TWILIO_FROM", "")

# Google Wallet — ruta al JSON de la cuenta de servicio y ID de emisor.
GOOGLE_WALLET_SERVICE_ACCOUNT = os.environ.get("GOOGLE_WALLET_SERVICE_ACCOUNT", "")
GOOGLE_WALLET_ISSUER_ID = os.environ.get("GOOGLE_WALLET_ISSUER_ID", "")
